name: Feature Request
description: Suggest a new feature or improvement
labels: ['enhancement']
body:
  - type: markdown
    attributes:
      value: 'Thanks for the suggestion!'
  - type: textarea
    id: problem
    attributes:
      label: Problem or motivation
      description: What problem does this solve?
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: How should it work?
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any other approaches you considered?
